name: Deploy to OVH VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OVH_VPS_IP: 15.204.232.142  # Define the IP directly as an environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}  # Use GIT_TOKEN to clone private repo

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.OVH_SSH_KEY }}

      - name: Build Docker image locally
        run: docker build -t myapp:latest .

      - name: Deploy Docker image to OVH VPS
        run: |
          # Stop and remove any existing container
          ssh -o StrictHostKeyChecking=no root@$OVH_VPS_IP "docker stop myapp || true && docker rm myapp || true"
          # Copy Dockerfile or push image to a registry (optional)
          scp -o StrictHostKeyChecking=no ./Dockerfile root@$OVH_VPS_IP:/root
          # Rebuild and run the container
          ssh -o StrictHostKeyChecking=no root@$OVH_VPS_IP "docker build -t myapp:latest /root && docker run -d --name myapp -p 80:80 myapp:latest"
